name: Tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  integration:
    name: Integration tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false

      - name: Setup
        run: ./setup-integration.sh
        shell: bash

      - name: Run integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose integration_ -- --ignored

  build:
    name: Build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - name: cargo build tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-run
